[package]
name = "pong"
version = "0.1.0"
authors = ["AlexandruGG <alex.gidei@goodlord.co>"]
edition = "2018"
description = "A two-player version of the classic game 'Pong'"
license-file = "license.html"

[dependencies]
tetra = "0.5.0"
